### ISSUE TITLE
fetching channel contents fails in case of Redirects

### ISSUE THREAD

**Issue by memo33** [memo33/sc4pac-tools#24]
In case the `sc4pac-channel-contents.json` file is redirected, this fails pretty ungracefully:

```
Exception in thread "main" Exception in thread "zio-fiber-990031298" ujson.ParseException: expected json value got "<" at index 0
        at ujson.ParseException$.apply(Exceptions.scala:6)
        at ujson.ByteParser.die(ByteParser.scala:98)
        at ujson.ByteParser.parseTopLevel0(ByteParser.scala:353)
        at ujson.ByteParser.parseTopLevel(ByteParser.scala:323)
        at ujson.ByteParser.parse(ByteParser.scala:72)
        at ujson.InputStreamParser$.transform(InputStreamParser.scala:26)
        at ujson.Readable$$anon$1.transform(Readable.scala:24)
        at ujson.package$.transform(package.scala:4)
        at ujson.package$.read$$anonfun$1(package.scala:10)
        at upickle.core.TraceVisitor$.withTrace(TraceVisitor.scala:18)
        at ujson.package$.read(package.scala:10)
        at io.github.memo33.sc4pac.MetadataRepository$.create$$anonfun$3(MetadataRepository.scala:88)
        at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:108)
        at zio.ZIO$.suspendSucceed$$anonfun$1(ZIO.scala:4823)
        at io.github.memo33.sc4pac.MetadataRepository.create(MetadataRepository.scala:88)
…
```

```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by memo33** [comment]
Actually, I cannot reproduce this now. Following 301 redirects does work. Possibly this was caused by a temporary server misconfiguration.

**Comment by Zasco** [comment]
I think it happened to me once too.
